name: Demo
on: 
  workflow_dispatch:
    inputs:
      service:
        description: 'service name'
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      DEPLOY_EVN: staging
    steps:
      - name: Checkout the repo
        run: |
          echo "Information : ${{ github.event.inputs.service }}"
          echo "Environment variable : $DEPLOY_EVN"
          echo "Repository secrets : ${{ secrets.SOME_TOKEN }}"
          echo "Repository variables : ${{ vars.COMPANY_NAME }}"